58. Please write a program using generator to print the even numbers between 0 and n in comma
separated form while n is input by console.
Example: If the following n is given as input to the program: 10
Then, the output of the program should be: 0,2,4,6,8,10
Hints: Use yield to produce the next value in generator. In case of input data being supplied to the
question, it should be assumed to be a console input.|

In [18]:
def gen(a):
    for i in range(0,a+1):
        if i % 2 == 0:
            yield i
while True:
    n = int(input("enter n value:"))
    if n < 0:
        print("enter positive value")
    else:
        for i in gen(n):
            print(i,end=",")
        
        break

enter n value:10
0,2,4,6,8,10,

59. Please write a program using generator to print the numbers which can be divisible by 5 and 7
between 0 and n in comma separated form while n is input by console.
If the following n is given as input to the program: 100
Then, the output of the program should be: 0, 35, 70 
Hints: Use yield to produce the next value in generator. In case of input data being supplied to the
question, it should be assumed to be a console input.

In [19]:
def gen(a):
    for i in range(0,a+1):
        if (i % 5 == 0) and (i%7 == 0):
            yield i
while True:
    n = int(input("enter n value:"))
    if n<0:
        print("n should be positive")
    else:
        for i in gen(n):
            print(i,end=",")
        break

enter n value:100
0,35,70,

60. Please write assert statements to verify that every number in the list [2,4,6,8] is even.
Hints: Use "assert expression" to make assertion.

In [25]:
l = [2,4,6,8]
for i in l:
    assert i % 2 == 0, "even"
    print("element {} is even".format(i))

element 2 is even
element 4 is even
element 6 is even
element 8 is even


61. Please write a program which accepts basic mathematic expression from console and print the
evaluation result.
If the following string is given as input to the program: 35+3
Then, the output of the program should be: 38
Hints: Use eval() to evaluate an expression.

In [36]:
eval(input("enter expression:"))

enter expression:35+3


38

62. Please write a binary search function which searches an item in a sorted list. The function should
return the index of element to be searched in the list.
Hints: Use if/elif to deal with conditions.

In [40]:
def search(l,a):
    l = sorted(l)
    for i in l:
        if i == a:
            return l.index(i)
l = [0,1,8,6,7,4]
ans = search(l,6)
print(ans)

3


63. Please write a binary search function which searches an item in a sorted list. The function should
return the index of element to be searched in the list.
Hints: Use if/elif to deal with conditions

In [41]:
def search(l,a):
    l = sorted(l)
    for i in l:
        if i == a:
            return l.index(i)
l = [0,1,8,6,7,4]
ans = search(l,6)
print(ans)

3


64. Please generate a random float where the value is between 10 and 100 using Python math module.
Hints: Use random.random() to generate a random float in [0,1].

In [56]:
import numpy as np
n = np.random.uniform(10,100)
print(n)

35.13541245357452


65. Please generate a random float where the value is between 5 and 95 using Python math module.
Hints: Use random.random() to generate a random float in [0,1].

In [57]:
import numpy as np
n = np.random.uniform(5,95)
print(n)

86.11837015056626


66. Please write a program to output a random even number between 0 and 10 inclusive using random
module and list comprehension.
Hints: Use random.choice() to a random element from a list.

In [72]:
import numpy as np
ans = np.random.choice([i for i in range(0,11) if i % 2 == 0],1)
print(ans)

[4]


67. Please write a program to output a random number, which is divisible by 5 and 7, between 0 and 10
inclusive using random module and list comprehension.
Hints: Use random.choice() to a random element from a list.

In [73]:
import numpy as np
ans = np.random.choice([i for i in range(0,11) if (i%5 == 0) and (i%7 == 0)],1)
print(ans)

[0]


68. Please write a program to generate a list with 5 random numbers between 100 and 200 inclusive.
Hints: Use random.sample() to generate a list of random values.

In [78]:
import numpy as np
ans = np.random.choice([i for i in range(100,201)],5)
print(ans)

[120 168 154 196 123]


69. Please write a program to randomly generate a list with 5 even numbers between 100 and 200
inclusive.
Hints: Use random.sample() to generate a list of random values.

In [84]:
import numpy as np
ans = np.random.choice([i for i in range(100,201) if i % 2 == 0],5)
print(ans)

[146 146 166 126 146]


70. Please write a program to randomly generate a list with 5 numbers, which are divisible by 5 and 7 ,
between 1 and 1000 inclusive.
Hints: Use random.sample() to generate a list of random values.

In [85]:
import numpy as np
ans = np.random.choice([i for i in range(1,1001) if (i%5 == 0) and (i%7 == 0)],5)
print(ans)

[560 105 980 140 595]


71. Please write a program to randomly print a integer number between 7 and 15 inclusive.
Hints: Use random.randrange() to a random integer in a given range.

In [88]:
import numpy as np
ans = np.random.randint(7,16)
print(ans)

12


72. Please write a program to print the running time of execution of "1+1" for 100 times.
Hints: Use timeit() function to measure the running time.

In [102]:
import timeit
a = "1+1"
print(timeit.timeit(stmt = a,number = 100))

1.5000005078036338e-06


73. Please write a program to shuffle and print the list [3,6,7,8].
Hints: Use shuffle() function to shuffle a list.

In [110]:
import numpy as np
import random
l = [3,6,7,8]
random.shuffle(l)
print(l)

[6, 8, 3, 7]


74. Please write a program to shuffle and print the list [3,6,7,8]. Hints: Use shuffle() function to shuffle a list.

In [111]:
import random
l = [3,6,7,8]
random.shuffle(l)
print(l)

[8, 6, 7, 3]


75. Please write a program to generate all sentences where subject is in ["I", "You"] and verb is in
["Play", "Love"] and the object is in ["Hockey","Football"].
Hints: Use list[index] notation to get a element from a list.

In [114]:
subjects = ["I","You"]
verb = ["Play","Love"]
objects = ["Hockey", "Footbal"]
for i in range(len(subjects)):
    for j in range(len(verb)):
        for k in range(len(objects)):
            print(subjects[i] +" "+ verb[j] +" "+ objects[k])
            

I Play Hockey
I Play Footbal
I Love Hockey
I Love Footbal
You Play Hockey
You Play Footbal
You Love Hockey
You Love Footbal


76. Please write a program to print the list after removing delete even numbers in [5,6,77,45,22,12,24].
Hints: Use list comprehension to delete a bunch of element from a list.

In [115]:
l = [5,6,77,45,22,12,24]
l = [i for i in l if i %2 != 0]
print(l)

[5, 77, 45]


77. By using list comprehension, please write a program to print the list after removing delete numbers
which are divisible by 5 and 7 in [12,24,35,70,88,120,155].
Hints: Use list comprehension to delete a bunch of element from a list.

In [117]:
l = [12,24,35,70,88,120,155]
l = [i for i in l if (i % 5 != 0) and (i % 7 !=0)]
print(l)

[12, 24, 88]


78. By using list comprehension, please write a program to print the list after removing the 0th, 2nd,
4th,6th numbers in [12,24,35,70,88,120,155].
Hints: Use list comprehension to delete a bunch of element from a list. Use enumerate() to get (index,
value) tuple.

In [12]:
l = [12,24,35,70,88,120,155]
new = list(enumerate(l))
print(new)
ans = [i[1] for i in new if i[0]%2 != 0]
ans

[(0, 12), (1, 24), (2, 35), (3, 70), (4, 88), (5, 120), (6, 155)]


[24, 70, 120]

79. By using list comprehension, please write a program generate a 3*5*8 3D array whose each element is 0.
Hints: Use list comprehension to make an array.

In [21]:
x = [[[0 for i in range(0,5)] for j in range(0,3)] for k in range(0,5)]
print(x)

[[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]]


80. By using list comprehension, please write a program to print the list after removing the 0th,4th,5th numbers in [12,24,35,70,88,120,155].
Hints: Use list comprehension to delete a bunch of element from a list. Use enumerate() to get (index, value) tuple.

In [25]:
l = [12,24,35,70,88,120,155]
new = list(enumerate(l))
ans = [i[1] for i in new if (i[0] !=0) and (i[0] !=4) and (i[0] !=5)]
print(ans)

[24, 35, 70, 155]


81. By using list comprehension, please write a program to print the list after removing the value 24 in [12,24,35,24,88,120,155].
Hints: Use list's remove method to delete a value.

In [29]:
l = [12,24,35,24,88,120,155]
l.remove(24)
l.remove(24)
print(l)

[12, 35, 88, 120, 155]


82. With two given lists [1,3,6,78,35,55] and [12,24,35,24,88,120,155], write a program to make a list whose elements are intersection of the above given lists.
 Hints: Use set() and "&=" to do set intersection operation.

In [38]:
l1 = [1,3,6,78,35,55]
l2 =[12,24,35,24,88,120,155]
set1 = set(l1)
set2 = set(l2)
print(list(set1 & set2))


[35]


83. With a given list [12, 24, 35, 24, 88, 120, 155, 88, 120, 155], write a program to print this list after removing all duplicate values with original order reserved.
Hints: Use set() to store a number of values without duplicate.

In [40]:
l = [12, 24, 35, 24, 88, 120, 155, 88, 120, 155]
print(list(set(l)))

[35, 12, 155, 24, 88, 120]


84. Please write a program which count and print the numbers of each character in a string input by console.
If the following string is given as input to the program: abcdefgabc
Then, the output of the program should be:
a,2
c,2
b,2
e,1
d,1
g,1
f,1
Hints: Use dict to store key/value pairs. Use dict.get() method to lookup a key with default value.

In [50]:
n = input("enter string:")
d = {}
for i in n:
    d[i] = n.count(i)
for i in d:
    print("{}, {}".format(i,d.get(i)))

enter string:abcdefgabc
a, 2
b, 2
c, 2
d, 1
e, 1
f, 1
g, 1


85. Please write a program which accepts a string from console and print it in reverse order.
If the following string is given as input to the program: rise to vote sir
Then, the output of the program should be: ris etov ot esir
Hints: Use list[::-1] to iterate a list in a reverse order.

In [52]:
n = input("enter string")
print(n[::-1])

enter stringrise to vote sir
ris etov ot esir


86. Please write a program which accepts a string from console and print the characters that have even indexes.
If the following string is given as input to the program: H1e2l3l4o5w6o7r8l9d
Then, the output of the program should be: Helloworld
Hints: Use list[::2] to iterate a list by step 2.

In [1]:
n = input("enter string:")
n[::2]

enter string:H1e21314o5w6o7r819d


'He11owor1d'

87. Please write a program which prints all permutations of [1, 2, 3]
Hints: Use itertools.permutations() to get permutations of list.

In [3]:
from itertools import permutations
l = [1,2,3]
p = list(permutations(l))
print(p)

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


89. Write a program to solve a classic ancient Chinese puzzle:
We count 35 heads and 94 legs among the chickens and rabbits in a farm. How many rabbits and how many chickens do we have?
Hint: Use for loop to iterate all possible solutions

In [7]:
nheads = 35
nlegs = 94
for i in range(nheads+1):
    j = nheads - i
    if (2*i)+(4*j) == nlegs:
        print("number of chichens are {} and number of rabbits are {}".format(i,j))

number of chichens are 23 and number of rabbits are 12
